"""Core data models for AlphaBot v4.0"""
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from datetime import datetime
from enum import Enum
import uuid


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


class RegimeType(str, Enum):
    BULL_TREND = "bull_trend"
    BEAR_TREND = "bear_trend"
    HIGH_VOL = "high_vol"
    LOW_VOL = "low_vol"
    RANGE_BOUND = "range_bound"
    CRASH = "crash"


class StrategyState(str, Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    KILLED = "killed"


class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"
    VWAP = "vwap"
    TWAP = "twap"


class CircuitState(str, Enum):
    CLOSED = "closed"
    OPEN = "open"
    HALF_OPEN = "half_open"


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    symbol: str
    direction: Direction
    confidence: float
    entry_price: float
    stop_loss: float
    take_profit: float
    position_size: float
    strategy_id: str
    cluster: str = ""
    timestamp: str = ""
    signal_id: str = ""
    metadata: Dict = field(default_factory=dict)

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.utcnow().isoformat()
        if not self.signal_id:
            self.signal_id = str(uuid.uuid4())[:8]


@dataclass
class Position:
    """Active trading position"""
    symbol: str
    direction: Direction
    quantity: int
    entry_price: float
    current_price: float
    stop_loss: float
    take_profit: float
    strategy_id: str
    signal_id: str
    entry_time: str
    position_id: str = ""
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    highest_price: float = 0.0
    lowest_price: float = float('inf')
    tranche: int = 1

    def __post_init__(self):
        if not self.position_id:
            self.position_id = str(uuid.uuid4())[:8]
        if self.highest_price == 0:
            self.highest_price = self.entry_price
        if self.lowest_price == float('inf'):
            self.lowest_price = self.entry_price

    def update_price(self, price: float):
        self.current_price = price
        self.highest_price = max(self.highest_price, price)
        self.lowest_price = min(self.lowest_price, price)
        if self.direction == Direction.LONG:
            self.unrealized_pnl = (price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - price) * self.quantity

    def to_dict(self):
        return {
            "position_id": self.position_id,
            "symbol": self.symbol,
            "direction": self.direction.value,
            "quantity": self.quantity,
            "entry_price": round(self.entry_price, 2),
            "current_price": round(self.current_price, 2),
            "stop_loss": round(self.stop_loss, 2),
            "take_profit": round(self.take_profit, 2),
            "strategy_id": self.strategy_id,
            "unrealized_pnl": round(self.unrealized_pnl, 2),
            "realized_pnl": round(self.realized_pnl, 2),
            "entry_time": self.entry_time,
            "pnl_pct": round((self.unrealized_pnl / (self.entry_price * self.quantity)) * 100, 2) if self.quantity else 0
        }


@dataclass
class Trade:
    """Completed trade record"""
    trade_id: str
    symbol: str
    direction: Direction
    quantity: int
    entry_price: float
    exit_price: float
    pnl: float
    pnl_pct: float
    strategy_id: str
    entry_time: str
    exit_time: str
    exit_reason: str
    slippage: float = 0.0
    commission: float = 0.0

    def to_dict(self):
        return {
            "trade_id": self.trade_id,
            "symbol": self.symbol,
            "direction": self.direction.value,
            "quantity": self.quantity,
            "entry_price": round(self.entry_price, 2),
            "exit_price": round(self.exit_price, 2),
            "pnl": round(self.pnl, 2),
            "pnl_pct": round(self.pnl_pct, 2),
            "strategy_id": self.strategy_id,
            "entry_time": self.entry_time,
            "exit_time": self.exit_time,
            "exit_reason": self.exit_reason
        }


@dataclass
class RegimeResult:
    """Market regime detection result"""
    regime: RegimeType
    confidence: float
    hmm_regime: str = ""
    rule_regime: str = ""
    features: Dict = field(default_factory=dict)
    timestamp: str = ""

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.utcnow().isoformat()


@dataclass 
class AgentPrediction:
    """AI agent prediction output"""
    agent_name: str
    direction_probability: float
    confidence: float
    predicted_return: float = 0.0
    regime: str = ""
    rationale: str = ""
    metadata: Dict = field(default_factory=dict)
    timestamp: str = ""

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.utcnow().isoformat()


@dataclass
class PortfolioState:
    """Current portfolio state"""
    equity: float = 1_000_000.0
    cash: float = 1_000_000.0
    positions_value: float = 0.0
    daily_pnl: float = 0.0
    total_pnl: float = 0.0
    total_pnl_pct: float = 0.0
    long_exposure: float = 0.0
    short_exposure: float = 0.0
    net_exposure: float = 0.0
    gross_exposure: float = 0.0
    num_positions: int = 0
    peak_equity: float = 1_000_000.0
    drawdown: float = 0.0
    drawdown_pct: float = 0.0
    sharpe_ratio: float = 0.0
    win_rate: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    vix: float = 15.0
    regime: str = "range_bound"
    avg_correlation: float = 0.3
    sector_exposures: Dict[str, float] = field(default_factory=dict)
    strategy_drawdowns: Dict[str, float] = field(default_factory=dict)

    def to_dict(self):
        return {
            "equity": round(self.equity, 2),
            "cash": round(self.cash, 2),
            "positions_value": round(self.positions_value, 2),
            "daily_pnl": round(self.daily_pnl, 2),
            "total_pnl": round(self.total_pnl, 2),
            "total_pnl_pct": round(self.total_pnl_pct, 2),
            "long_exposure": round(self.long_exposure, 2),
            "short_exposure": round(self.short_exposure, 2),
            "net_exposure": round(self.net_exposure, 2),
            "gross_exposure": round(self.gross_exposure, 2),
            "num_positions": self.num_positions,
            "drawdown_pct": round(self.drawdown_pct, 2),
            "sharpe_ratio": round(self.sharpe_ratio, 2),
            "win_rate": round(self.win_rate, 2),
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "vix": round(self.vix, 2),
            "regime": self.regime
        }
